"""
Test statistical properties of generated panels.

Compares statistical properties (mean, std, correlation) of panels
generated by current vs original code. Uses same random seed.
"""

import sys
import os
import numpy as np
import pandas as pd
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'test_utils'))

from comparison import compute_summary_stats, print_comparison_summary
from config_override import TEST_N, TEST_T, TEST_BURNIN, TEST_SEED


def test_bgn_panel_statistics():
    """Compare statistical properties of BGN panels."""
    print("=" * 70)
    print("BGN Panel Statistical Properties")
    print("=" * 70)

    # Import both versions
    from utils_bgn import panel_functions_bgn as bgn_new
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    import panel_functions as bgn_old

    # Generate with current code
    print("\n[1/2] Generating panel with current code...")
    np.random.seed(TEST_SEED)
    arrays_new = bgn_new.create_arrays(TEST_N, TEST_T + TEST_BURNIN)
    panel_new = bgn_new.create_panel(TEST_N, TEST_T + TEST_BURNIN, arrays_new)

    # Generate with original code
    print("[2/2] Generating panel with original code...")
    np.random.seed(TEST_SEED)
    arrays_old = bgn_old.create_arrays(TEST_N, TEST_T + TEST_BURNIN)
    panel_old = bgn_old.create_panel(TEST_N, TEST_T + TEST_BURNIN, arrays_old)

    # Compare statistics
    print("\n[COMPARE] Statistical properties:")

    for col in ['ret', 'xret', 'bm', 'roe', 'inv', 'agr']:
        if col in panel_new.columns and col in panel_old.columns:
            new_vals = panel_new[col].dropna()
            old_vals = panel_old[col].dropna()

            print(f"\n  {col}:")
            print(f"    Mean:  new={new_vals.mean():.6f}, old={old_vals.mean():.6f}")
            print(f"    Std:   new={new_vals.std():.6f}, old={old_vals.std():.6f}")
            print(f"    Min:   new={new_vals.min():.6f}, old={old_vals.min():.6f}")
            print(f"    Max:   new={new_vals.max():.6f}, old={old_vals.max():.6f}")

    print("\n" + "=" * 70)
    return True


def test_kp14_panel_statistics():
    """Compare statistical properties of KP14 panels."""
    print("\n" + "=" * 70)
    print("KP14 Panel Statistical Properties")
    print("=" * 70)

    from utils_kp14 import panel_functions_kp14 as kp_new
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    import panel_functions_kp14 as kp_old

    np.random.seed(TEST_SEED)
    arrays_new = kp_new.create_arrays(TEST_N, TEST_T + TEST_BURNIN)
    panel_new = kp_new.create_panel(TEST_N, TEST_T + TEST_BURNIN, arrays_new)

    np.random.seed(TEST_SEED)
    arrays_old = kp_old.create_arrays(TEST_N, TEST_T + TEST_BURNIN)
    panel_old = kp_old.create_panel(TEST_N, TEST_T + TEST_BURNIN, arrays_old)

    print("\n[COMPARE] Statistical properties:")

    for col in ['ret', 'xret', 'bm', 'roe', 'inv']:
        if col in panel_new.columns and col in panel_old.columns:
            new_vals = panel_new[col].dropna()
            old_vals = panel_old[col].dropna()

            print(f"\n  {col}:")
            print(f"    Mean:  new={new_vals.mean():.6f}, old={old_vals.mean():.6f}")
            print(f"    Std:   new={new_vals.std():.6f}, old={old_vals.std():.6f}")

    print("\n" + "=" * 70)
    return True


if __name__ == "__main__":
    test_bgn_panel_statistics()
    test_kp14_panel_statistics()
